definitions: 
  steps:
  
    # Build
    - step: &build
        name: Install and Test
        image: node:16
        script:
          - npm install --legacy-peer-deps
          - 

     # Deployment
     - step: &deploy
        name: Deploy Artifacts
        trigger: automatic
        deployment: test
        script:
          - npm run build
          # Deploy New Artifact
          - pipe: atlassian/sftp-deploy:0.5.11
            variables:
             USER: 'dvaleram'
             SERVER: '217.160.13.34'
             REMOTE_PATH: '/var/www/vhosts/valera-melendez.de/anwalt.valera-melendez.de/'
            LOCAL_PATH: 'build'
            PASSWORD: D44378472v.?


# Runner
pipelines:

  branches:

    master: