// You can customize the layout of dashboard per user's role

const menuConfig = {
  Admin: {
    emailApp: true,
    documentApp: true,
    chatApp: true,
    taskApp: true,
    calendarApp: true,
    respiteApp: true,
    outboxApp: true,
    billsApp: true,
    contactApp: true,
    userApp: true,
    accountApp: true,
    emailTemplateApp: true,
    cloudServerApp: true,
    letterTemplateApp: true,
    calendarSettingApp: true,
    voiceRecordingApp: true,
    importLetterFileApp: true
  },
  Lawyer: {
    emailApp: true,
    documentApp: true,
    chatApp: true,
    taskApp: true,
    calendarApp: true,
    respiteApp: true,
    outboxApp: true,
    billsApp: true,
    contactApp: true,
    userApp: true,
    accountApp: true,
    emailTemplateApp: true,
    cloudServerApp: true,
    letterTemplateApp: true,
    calendarSettingApp: true,
    voiceRecordingApp: true,
    importLetterFileApp: true
  },
  Partner: {
    emailApp: true,
    documentApp: true,
    chatApp: true,
    taskApp: true,
    calendarApp: true,
    respiteApp: true,
    outboxApp: true,
    billsApp: true,
    contactApp: true,
    userApp: true,
    accountApp: true,
    emailTemplateApp: true,
    cloudServerApp: true,
    letterTemplateApp: true,
    calendarSettingApp: true,
    voiceRecordingApp: true,
    importLetterFileApp: true
  },
  Customer: {
    emailApp: true,
    documentApp: true,
    chatApp: true,
    taskApp: true,
    calendarApp: true,
    respiteApp: true,
    outboxApp: true,
    billsApp: true,
    contactApp: true,
    userApp: true,
    accountApp: true,
    emailTemplateApp: true,
    cloudServerApp: true,
    letterTemplateApp: true,
    calendarSettingApp: true,
    voiceRecordingApp: true,
    importLetterFileApp: true
  }
}

export default menuConfig
